export const m = {
    "actionYes": "Yes",
    "actionNo": "No",
    "actionDoNotAskAgain": "Don't ask again",
    "actionOK": "OK",
    "actionOpenSetting": "Open setting",
    "noKeyInCurrentFolder": "Unable to retrieve any key in current folder.",
    "passphraseInputPromptTitle": "Input the passphrase for the signing key",
    "keyDescriptionWithUserId": "For the key associated with {0}",
    "passphraseStored": "The passphrase is stored in the SecretStorage of VSCode.",
    "keyUnlocked": "Key unlocked.",
    "keyUnlockFailedWithId": "Failed to unlock: {0}",
    "noCachedPassphraseForCurrentKey": "There is no cached passphrase for your current key.",
    "cachedPassphraseListForDeletion": "List of keys with stored passphrases, select to delete.",
    "cachedPassphraseListForDeletionPlaceHolder": "You can search the fingerprint and user id in this search box.",
    "passphraseDeleted": "Your cached passphrase has been deleted.",
    "noCachedPassphrase": "There is no cached passphrase.",
    "currentKey": "Current key",
    "restKey": "Rest keys",
    "cachedPassphraseList": "List of keys with stored passphrases:",
    "passphraseCleared": "All Your cached passphrase has been cleared.",
    "keyAutomaticallyUnlocked": "Key unlocked automatically using the previous-used stored passphrase.",
    "keyAutomaticallyUnlockFailed": "The previous-used stored passphrase is unable to unlock current key.",
    "keyChanged": "Key changed.",
    "keyRelocked": "Key re-locked.",
    "noActiveFolder": "No active folder",
    "noKeyForCurrentFolder": "No key for current folder",
    "enableSecurelyPassphraseCacheNotice": "GPG Indicator come with new passphrase cache feature, would you like to enable this feature?",
    "enableSecurelyPassphraseCacheNoticeForbidden": "OK, you can configure it later in setting.",
    "enableSecurelyPassphraseCacheNoticeAgreed": "OK, this feature has been enabled, you can configure it later in setting."
};
